apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sa-demo-ingress
  labels:
    app: sa-demo
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: sa-demo.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: sa-demo-service
            port:
              number: 80

