apiVersion: v1
kind: Service
metadata:
  name: sa-demo-service
  labels:
    app: sa-demo
spec:
  type: LoadBalancer
  selector:
    app: sa-demo
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  sessionAffinity: ClientIP

